#!/bin/bash
apt install screen figlet toilet cowsay -y > /dev/null
rm /tmp/finish
figlet -c "Script"
figlet -c "de"
figlet -c "Instalacao"
figlet -c "Unbound"
figlet -c "Iuniti Services"
echo "Iuniti services, script de instalação para o Unbound. By Marco totalmente automatizado."
sleep 7

apt-get install unbound nano wget dnsutils dnstop zabbix-agent htop -y
chown unbound.unbound /etc/unbound/ -R
rm /etc/unbound/unbound.conf.d/root-auto-trust-anchor-file.conf
wget https://raw.githubusercontent.com/iuniti/unbound/master/iuniti.conf
mv iuniti.conf /etc/unbound/unbound.conf.d/
wget http://www.internic.net/domain/named.root
mv named.root /etc/unbound/root.hints
unbound-anchor -v
echo 127.0.0.1 > /etc/resolv.conf
/etc/init.d/unbound stop
/etc/init.d/unbound start
ps ax | grep unbound
echo "confira se o Unbound esta rodando"
sleep 7


sed -i 's/^# Server=.*/Server=138.0.115.13,2804:213c:1::13,iuniti..com.br/' /etc/zabbix/zabbix_agentd.conf
sed -i 's/^# Hostname=.*/Hostname=ns1.recursivo/' /etc/zabbix/zabbix_agentd.conf
/etc/init.d/zabbix-agent restart

cowsay -f tux Instalacao Finalizada
figlet -c By Iuniti Services
